# Generated by Django 5.2.4 on 2025-08-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chat", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
