# Generated by Django 5.2.4 on 2025-08-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_unreadmessagesmanager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UnreadMessagesManager",
        ),
    ]
