# Generated by Django 5.2.4 on 2025-08-01 19:08

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0006_delete_unreadmessagesmanager"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="message",
            managers=[
                ("unread", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
