# Generated by Django 5.2.4 on 2025-08-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0007_alter_message_managers_message_read"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="message",
            managers=[],
        ),
    ]
